### ISSUE TITLE
Columns body classes are not working

### ISSUE THREAD

**Issue by montalvomiguelo** [woothemes/woocommerce#11554]
We have styles for WooCommerce body classes at __woocommerce-layout.css__
```css
.woocommerce-page.columns-1 ul.products li.product,
.woocommerce.columns-1 ul.products li.product {
  width: 100%;
  margin-right: 0
}
.woocommerce-page.columns-2 ul.products li.product,
.woocommerce.columns-2 ul.products li.product {
  width: 48%
}
.woocommerce-page.columns-3 ul.products li.product,
.woocommerce.columns-3 ul.products li.product {
  width: 30.75%
}
.woocommerce-page.columns-5 ul.products li.product,
.woocommerce.columns-5 ul.products li.product {
  width: 16.95%
}
.woocommerce-page.columns-6 ul.products li.product,
.woocommerce.columns-6 ul.products li.product {
  width: 13.5%
}
```

I wanted to filter the number of columns to 3 in my theme:

```php
<?php

// Override theme default specification for product # per row
function loop_columns() {
  return 3; // 3 products per row
}
add_filter('loop_shop_columns', 'loop_columns', 999);
```

But that _columns_ classes are not being added at the body:

```html
<body class="archive post-type-archive post-type-archive-product woocommerce woocommerce-page woocommerce-activated custom-font-enabled single-author">
...
</body>
```
