### ISSUE TITLE
Run smoke tests against external host based on label

### ISSUE THREAD

**Issue by zhongruige** [woothemes/woocommerce#30614]
We want to add a workflow that runs the e2e test suite against a particular host. We can create a workflow that has something like this:

```yaml
name: prcheck
on:
  pull_request:
    types:
      - labeled
jobs:
  prcheck:
    if: github.event.label.name == 'runtest'
```
