### ISSUE TITLE
Add e2e tests for `Set up shipping` task

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33474]
**Issue Description:**

Add e2e tests for `Set up shipping` task

```
- Merchant can set up shipping costs through the onboarding task
  - Merchant can manually set up shipping costs
  - Merchant can set up shipping costs with WCS and Jetpack if store location is the US
  - Smart defaults should be applied when the  store matches some conditions.
```

**Acceptance criteria**

**For current design:**

```yml
Given: a merchant sells physical products
  - and: haven't set up shipping costs/zones
When: a merchant goes Woocommerce > Home
Then: a merchant should see the shipping task

When: a merchant goes to the shipping task
  - and complete item on each step
Then: notices should be shown on steps 2 and 3

When: a merchant completes all steps
Then:
  - the task should be marked as completed
  
Given: a merchant sells physical products
  - and: set up shipping costs/zones
When: a merchant click the shipping task
  Then: a merchant should be redirected to the shipping setting page.
```

**For new design**
TBD
