### ISSUE TITLE
Add e2e tests for `Set up Additional Payments` task

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33477]
**Issue Description:**

Add e2e tests for `Set up Additional Payments` task

```
- Merchant can set up additional payments through the onboarding task
  - Merchant can set up an additional payment with payment providers.
  - Merchant can set up `Direct bank transfer`
  - Merchant can enable `Cash on delivery`
```

**Acceptance criteria**

```yml
Given: WC Pay is installed via OBW
  - and: WC Pay is connected
  - and the store is located in a WCPay supported country
 
When: a merchant goes to Woocommerce > Home
Then: a merchant should see the `Set up additional payment providers` task under `Things to do next`

When: a merchant clicks `Set up additional payment providers` task
Then: 
   - a merchant should see a list of payment providers
   - a merchant should see offline payment methods
   - a merchant can set up `Direct bank transfer`
   - a merchant can enable `Cash on deliver`

When: a merchant chooses a payment provider
Then: a merchant can install and set up a payment provider

When: one of the actions is done
Then: the task should be marked as completed.
```

Update:

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/tests/e2e-pw/tests/admin-tasks/payment.spec.js

I just noticed that we already have e2e tests for the payment task. So, I think we can just review the existing tests and see if we need to add more test cases for it.
