### ISSUE TITLE
Add e2e tests for `Add my products` task

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33472]
**Issue Description:**

Add e2e tests for the `Add my products` task.

```
- Merchant can add products through the onboarding task
 1. Merchant can add products with product templates
 2. Merchant can add products manually
 3. Merchant can import products with a CSV file
```

**Acceptance criteria**

```yml
Given: a new merchant

When: a merchant goes to `Add my products` task
  - and: chooses a product template 
Then: a merchant should be redirected to the product page with pre-filled content (selected product type).
  - When: a merchant clicks the "publish" button
    Then: `Congrats on adding your first product!` notice should be shown

When: a merchant goes to `Add my products` task
  - and: chooses "Add manually" option 
Then: a merchant should be redirected to the product page with empty content.
  - When: a merchant clicks the "publish" button
    Then: `Congrats on adding your first product!` notice should be shown

When: a merchant goes to `Add my products` task
  - and: chooses "Import via CSV" option 
Then: a merchant should be redirected to import CSV flow. (Just need to test it get redirected to the page; We already have e2e tests for import CSV flow.)
```
