### ISSUE TITLE
Add e2e tests for `Set up tax rates` task

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33473]
**Issue Description:**

Add e2e tests for the `Set up tax rates`.

```
- Merchant can set up tax rates through the onboarding task
  - Merchant can see Avalara plugin given the store location is not in `'US', 'CA', 'AU', 'GB'
  - Merchant can see "WC Tax" plugin given the store location is in `'US', 'CA', 'AU', 'GB'
  - Merchant can install a tax plugin
  - Merchant can set up tax manually
  - Merchant can dismiss the task by clicking "I don't charge sales tax" button
```

**Acceptance criteria**

```yml
#  I think we can just add frontend unit tests for the following cases
Given: a store location is not in `'US', 'CA', 'AU', 'GB'`
When: a merchant goes to Set up tax rates task
Then: a merchant should see the `Avalara` plugin as a recommended extension, but not `WC Tax` plugin.

Given: a store location is in `'US', 'CA', 'AU', 'GB'`
When: a merchant goes to Set up tax rates task
Then: a merchant should see the `WC Tax` plugin and `Avalara` plugin as recommended extensions.
```

```yml
Given: a merchant hasn't installed a recommended plugin
When: a merchant clicks the `Enable & Set up` button of a recommended plugin
Then:
  - a merchant can install a tax plugin
  - the task should be marked as completed once the plugin is installed

Given: a merchant hasn't set up tax rates
When: a merchant clicks the `Set up taxes manually ` button
Then:
   - a merchant should be redirected to the tax setting page 
   - when: a merchant adds a tax row
     Then: a merchant should see the success notice.

Given: a merchant hasn't set up tax rates
When: a merchant clicks the `I don't charge sales tax` button
Then: a merchant should be redirected to the Home page and the tax task is marked as completed.
```
