### ISSUE TITLE
Add e2e tests for `Grow your business` task

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33475]
**Issue Description:**

Add e2e tests for `Set up marketing tools` task

```
- Merchant can set up marketing tools through the things to do next task
  - Merchant can see the recommended marketing extensions
  - Merchant can install a marketing extension 
  - Merchant can see the task marked as completed when a marketing extension is installed.
```

**Acceptance criteria**

```yml
Given: a merchant hasn't installed any marketing extensions 
When: a merchant goes to `Grow your business` task:
Then:
  - a merchant should see the recommended marketing extensions under `REACH OUT TO CUSTOMERS`
  - a merchant should see the recommended marketing extensions under `GROW YOUR STORE`.
  - a merchant can install a marketing extension by clicking `Get started` button.

Given: a merchant has installed a marketing extension
When: a merchant goes to `Woocommerce > Home`
Then: The `Set up marketing tools` task should be marked as completed.
```
