### ISSUE TITLE
Add e2e tests for `Personalize my store` task

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#33476]
**Issue Description:**

Add e2e tests for `Personalize my store` task

```
- Merchant can personalize their store through the onboarding task
  - Merchant can import sample products
  - Merchant can create a homepage
  - Merchant can upload a logo
  - Merchant can set a store notice
```

**Acceptance criteria**

```yml
Given: a store haven't set up a home page
  - and: has no products
When: a merchant goes to "Personalize my store" task
Then:
  - A merchant should see the `Import sample products` step
  - When:  a merchant completes the item on each step
  - Then: a notice should be shown.

When: All steps are completed
Then: 
  - The task should be marked as completed
  - A merchant should see sample products on the product page.
  - A merchant should see a personalized Home page
```
