### ISSUE TITLE
Documentation: Local development setup

### ISSUE THREAD

**Issue by tjcafferkey** [woothemes/woocommerce#49107]
Our existing documentation provides instructions on how to build the WooCommerce plugin. However, it lacks guidance on setting up and running the plugin within a local development environment.

Developers, especially those new to WooCommerce development, may struggle to get the plugin working in their local environment after building it. This can lead to frustration and delays in the development process.

**Proposed Solution:**

Update our documentation to include comprehensive guides for setting up WooCommerce in popular local development environments. This should cover:

1. [Studio by WordPress.com](https://developer.wordpress.com/studio/)
2. [LocalWP](https://localwp.com/)
3. [@wordpress/env package](https://www.npmjs.com/package/@wordpress/env)

**Comment by helgatheviking** [comment]
To add to your list... here's my `lando.yml` for using [Lando](https://lando.dev/)

```
name: sandbox
recipe: wordpress
config:
  webroot: .
  php: '8.3'
  database: mariadb
  via: nginx
  xdebug: false
  ssl: true
proxy:
  mailhog:
    - mail.sandbox.lndo.site
  phpmyadmin:
    - phpmyadmin.sandbox.lndo.site
services:
  database:
    portforward: true
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin
  appserver:
    overrides:
      volumes:
        - >-
          ../../woocommerce/plugins/woocommerce:/app/wp-content/plugins/woocommerce
        - >-
          ../../woocommerce/plugins/woocommerce-admin:/app/wp-content/plugins/woocommerce-admin
        - >-
          ../../woocommerce/plugins/woocommerce-blocks:/app/wp-content/plugins/woocommerce-blocks

```

Specifically it's the `appserver` overrides that get the WooCommerce mono-repo folders into the `wp-content/plugins` location.
