### ISSUE TITLE
[Enhancement]: Remove focus outline style from notice messages

### ISSUE THREAD

**Issue by Manussakis** [woothemes/woocommerce#51003]
### Describe the solution you'd like

After the [[Accessibility] Announce notice messages after page loads](https://github.com/woocommerce/woocommerce/pull/50061) PR was merged to fix the #43614 issue, the notice banner became a focusable element. However, this introduced a regression since the focus style makes the notice banner look awkward.

![image](https://github.com/user-attachments/assets/a17d625f-0d6a-4704-8c5e-72b1d9e0c8f9)

This CSS declaration should fix the issue:

```css
.wc-block-components-notice-banner {
	&:focus,
	&:focus-visible {
		outline: none;
	}
}
```
