### ISSUE TITLE
`Add To Cart Button` block has different style on the frontend side and editor side

### ISSUE THREAD

**Issue by gigitux** [woothemes/woocommerce#52626]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

`Add To Cart Button` block has different style on the frontend side and editor side:

| Editor | Frontend |
|--------|--------|
| ![Image](https://github.com/user-attachments/assets/5ea9a4fb-c612-491d-b7c8-cebc05971d7c)| ![Image](https://github.com/user-attachments/assets/bdd09e33-f07d-4d8c-8f27-ce42af51f396)| 

### Expected behavior

The frontend should match with the frontend preview.

### Actual behavior

In the editor, the button has a border radius, but it does not on the frontend.

### Steps to reproduce

1. Install and enable TT5.
2. Open the Site Editor.
3. Visit the `Product Catalog` template.
4. Ensure that the `Add To Cart Button` block has the border radius.
5. Visit the `/shop` page.
6. The `Add To Cart Button` block doesn't have the border radius.

### WordPress Environment

-

### Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by danielwrobert** [comment]
Another potentially related find: when there is no explicit width set on the button in the editor, the button width defaults to 100% of the container. However, on the front-end that's not the case:

| Editor | Frontend |
|--------|--------|
| ![Image](https://github.com/user-attachments/assets/84a3f9f2-2939-461d-8d9e-689786bccc21) | ![Image](https://github.com/user-attachments/assets/be0aa77a-1a04-4008-8deb-8d36e215c782) |

Note that this is not specific to TT5, I can also reproduce in TT4.

**Comment by retrofox** [comment]
This is an exciting issue.
In short, the styles of this `woocommerce/product-button` block relies on the `core/button` one.
You can confirm that by adding an instance of the `core/buttons` into the template. Save it. Hard refresh.

Under the hood, the button element gets the styles through the `.wp-block-button__link` CSS class:

```css
.wp-block-button__link{
  box-sizing:border-box;
  cursor:pointer;
  display:inline-block;
  text-align:center;
  word-break:break-word;
}
.wp-block-button__link.aligncenter{
  text-align:center;
}
.wp-block-button__link.alignright{
  text-align:right;
}

:where(.wp-block-button__link){
  border-radius:9999px;
  box-shadow:none;
  padding:calc(.667em + 2px) calc(1.333em + 2px);
  text-decoration:none;
}
```

However, this class is not loaded if the template page does not have a `core/button` instance
