### ISSUE TITLE
Related product CSS

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce#7873]
@jameskoster i'm not sure if this is a bug or not, but i don't understand it.

We have this code for the related products

```css
.woocommerce ul.products li.product,.woocommerce-page ul.products li.product {
    float: left;
    margin: 0 3.8% 2.992em 0;
    padding: 0;
    position: relative;
    width: 22.05%
}
```

BUT, we also have this

```css
.woocommerce .related ul li.product,.woocommerce .related ul.products li.product,.woocommerce .upsells.products ul li.product,.woocommerce .upsells.products ul.products li.product,.woocommerce-page .related ul li.product,.woocommerce-page .related ul.products li.product,.woocommerce-page .upsells.products ul li.product,.woocommerce-page .upsells.products ul.products li.product {
    width:48%
}
```

In some cases i've seen that it causes the related products image to be very big which is wrong.
Why do we have those 2 codes instead of only one?

I guess the second should be applied only on up-sells, right?
