### ISSUE TITLE
Breaking responsiveness of navigation menus with a css declaration

### ISSUE THREAD

**Issue by mberasategi** [woothemes/woocommerce#7950]
The theme I am using ([Agility](http://agility.sevenspark.com/)) makes the navigation menu responsive by adding a menu button for viewports less than 480px wide:

```html

<nav [...]>
    <a href="#main-nav-menu" class="mobile-menu-button button">
        Menu 
        <i class="icon-reorder"></i>
    </a>
</nav>
```

which, of course, is hidden for wider viewports (with `display:none;`). However, there is a declaration in `assets/css/woocommerce.css` ([line #587 of `assets/css/woocommerce.scss`](https://github.com/woothemes/woocommerce/blob/master/assets/css/woocommerce.scss#L587)) that breaks responsiveness of the navigation menu:

```css
.woocommerce #respond input#submit, 
.woocommerce a.button, 
.woocommerce button.button, 
.woocommerce input.button {
    [...]
    display: inline-block;
    [...]
}
```

Just making the `a.button` selector more specific would solve this issue -- however, I don't know if there is a default/general selector for the "main" area in Wordpress, excluding header, navigation and footer for example (I've seen both `#main` and `#main-container`) that could be used for the fix to be theme-independent... If there's not, then I will edit the plugin files manually for my installation (and re-do that after every update...).
